test: &default

  # Credentials for REST APIs
  client_id: AQ2h4x5EMcfm9kz4_Nk9nEJsEoRAFTJFuJEzr4jQvboBLuPP7odkWLD8R9GjcQgWBqPl6VOt1swV9TTR
  client_secret: EN8zEvHXk1eN77j8WynSjJhNDUxs3ZES26VeuH9j_vH4CFhA9jt8pu17AAIv1aqUT4G8isMX-xcDOMwE

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: kensanchez@ken.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  client_id: AfjNxtGPd_7gGtMc5xmoAnmLN-RQ2SVbKfYyRSPgs0PCnwztATOxxUZM3RdNJbqNTIhbeaYdiz-BpHxA
  client_secret: EOtEgwMCA_LQE23BDchmbWTaX3yv7-A1n547OxlGy6GLy0ehRhUtgISHaWxD5xdxEjMaXCBKL43gPKrY
  mode: live
